[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rec-gov-automate"
version = "0.1.0.dev0"
authors = [
  { name="Joel McCune (https://joelmccune.com)"},
]
description = "Automate tasks when interacting with Recreation.gov"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
license = {file = "LICENSE"}
dependencies = [
    "azure-communication-sms",
    "pandas",
    "pytest-playwright",
    "requests",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["rec_gov_automate"]
